<?xml version="1.0"?>
<robot name="bbot_diffential" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="bbot_diffential">
    <gazebo reference="imu_link">
        <gravity>true</gravity>
        <sensor name="imu_sensor" type="imu">
           <alwaysOn>true</alwaysOn>
           <update_rate>100</update_rate>
           <visualize>true</visualize>
           <topic>__default_topic__</topic>
           <plugin name="imu_plugin" filename="libgazebo_ros_imu_sensor.so">
           <!--alwaysOn>true</alwaysOn-->
           <bodyName>imu_link</bodyName>
           <frameName>imu_link</frameName>
           <topicName>imu_data</topicName>
           <!--serviceName>imu_service</serviceName-->
           <gaussianNoise>0.01</gaussianNoise>
           <updateRateHZ>10</updateRateHZ>
           <xyzOffset>0 0 0</xyzOffset>
           <rpyOffset>0 0 0</rpyOffset>
           <initialOrientationAsReference>false</initialOrientationAsReference>         
           </plugin>
           <pose>0 0 0 0 0 0</pose>
        </sensor>
    </gazebo>
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">

        <rosDebugLevel>Debug</rosDebugLevel>
        <publishWheelTF>false</publishWheelTF>
        <robotNamespace>/</robotNamespace>
        <publishTf>1</publishTf>
        <publishOdomTF>false</publishOdomTF>
        <publishWheelJointState>true</publishWheelJointState>
        <alwaysOn>true</alwaysOn>
        <updateRate>100.0</updateRate>
        <leftJoint>front_left_wheel_joint</leftJoint>
        <rightJoint>front_right_wheel_joint</rightJoint>
        <wheelSeparation>0.31</wheelSeparation>
        <wheelDiameter>${2*wheel_radius}</wheelDiameter>
        <broadcastTF>1</broadcastTF>
        <wheelTorque>30</wheelTorque>
        <wheelAcceleration>1.8</wheelAcceleration>
        <commandTopic>cmd_vel</commandTopic>
        <odometryFrame>odom</odometryFrame> 
        <odometryTopic>odom</odometryTopic>
        <odometrySource>1</odometrySource>
        <publishOdom>true</publishOdom> 
        <robotBaseFrame>base_footprint</robotBaseFrame>
        <legacyMode>false</legacyMode>
        </plugin>
    </gazebo>
  </xacro:macro>
</robot>    
